"use client";

import { useEffect, useState } from "react";
import { FileText, Download, Loader2 } from "lucide-react";
import AppShell from "@/components/layout/AppShell";
import { apiFetch } from "@/lib/apiClient";
import { downloadIncidentReportPDF } from "@/lib/pdfReport";

export default function ReportsPage() {
  const [reports, setReports] = useState([]);
  const [busyId, setBusyId] = useState(null);

  async function load() {
    const data = await apiFetch("/api/reports");
    setReports(data.reports);
  }

  useEffect(() => {
    load();
  }, []);

  async function handleDownload(reportId) {
    setBusyId(reportId);
    try {
      const data = await apiFetch(`/api/reports/${reportId}`);
      downloadIncidentReportPDF(data.report);
    } finally {
      setBusyId(null);
    }
  }

  return (
    <AppShell
      allowedRoles={["ADMIN", "SECURITY_ANALYST"]}
      title="Incident Reports"
      subtitle="Generated from the Alert Investigation page; download as PDF"
    >
      <div className="sx-card overflow-x-auto">
        <table className="sx-table w-full">
          <thead>
            <tr>
              <th>Report ID</th>
              <th>Title</th>
              <th>Generated By</th>
              <th>Date</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {reports.map((r) => (
              <tr key={r.reportId}>
                <td className="font-mono">{r.reportId}</td>
                <td style={{ color: "var(--sx-text)" }}>
                  <div className="flex items-center gap-2">
                    <FileText size={14} color="var(--sx-accent)" />
                    {r.title}
                  </div>
                </td>
                <td>{r.generatedBy?.name}</td>
                <td style={{ color: "var(--sx-text-dim)" }}>{new Date(r.createdAt).toLocaleString()}</td>
                <td>
                  <button className="sx-btn" disabled={busyId === r.reportId} onClick={() => handleDownload(r.reportId)}>
                    {busyId === r.reportId ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />} PDF
                  </button>
                </td>
              </tr>
            ))}
            {reports.length === 0 && (
              <tr>
                <td colSpan={5} className="text-center py-8" style={{ color: "var(--sx-text-dim)" }}>
                  No reports generated yet. Open an alert and click &quot;Generate Report&quot;.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </AppShell>
  );
}
