export const DEFAULT_DETECTION_RULES = [
  {
    ruleId: "RULE-PASSWORD-SPRAY",
    name: "Password Spray",
    description: "Detects many failed logins against many distinct users from a single source IP.",
    detectionType: "PASSWORD_SPRAY",
    severity: "HIGH",
    threshold: 5,
    distinctUserThreshold: 3,
    timeWindowMinutes: 5,
    mitreTechniqueId: "T1110.003",
    mitreTechniqueName: "Password Spraying",
    mitreTactic: "Credential Access",
    logicDescription: "More than 5 failed authentication attempts against 3 or more different users from the same IP within 5 minutes.",
  },
  {
    ruleId: "RULE-MFA-ABUSE",
    name: "Suspicious MFA Activity",
    description: "Detects repeated MFA resets, or an MFA reset immediately followed by a successful login.",
    detectionType: "MFA_ABUSE",
    severity: "HIGH",
    threshold: 2,
    timeWindowMinutes: 10,
    mitreTechniqueId: "T1621",
    mitreTechniqueName: "Multi-Factor Authentication Request Generation",
    mitreTactic: "Credential Access",
    logicDescription: "2 or more MFA resets for one user in 10 minutes, or an MFA reset followed by a successful login in the same window.",
  },
  {
    ruleId: "RULE-PRIVILEGE-ESCALATION",
    name: "Privilege Escalation",
    description: "Detects a user role being escalated to a more privileged role, especially after suspicious activity.",
    detectionType: "PRIVILEGE_ESCALATION",
    severity: "CRITICAL",
    timeWindowMinutes: 15,
    mitreTechniqueId: "T1098",
    mitreTechniqueName: "Account Manipulation",
    mitreTactic: "Persistence",
    logicDescription: "A user's role is changed to a higher-privilege role. Severity increases to CRITICAL if the new role is ADMIN.",
  },
  {
    ruleId: "RULE-UNUSUAL-ADMIN-LOGIN",
    name: "Unusual Admin Login",
    description: "Detects admin logins outside business hours, from a new IP, new device, or unusual location.",
    detectionType: "UNUSUAL_ADMIN_LOGIN",
    severity: "HIGH",
    timeWindowMinutes: 5,
    mitreTechniqueId: "T1078.003",
    mitreTechniqueName: "Valid Accounts: Local Accounts",
    mitreTactic: "Defense Evasion",
    logicDescription: "An admin account authenticates outside normal business hours, or from an IP/device/location outside their known baseline.",
  },
  {
    ruleId: "RULE-IMPOSSIBLE-TRAVEL",
    name: "Impossible Travel",
    description: "Detects two successful logins from different countries within an implausibly short window.",
    detectionType: "IMPOSSIBLE_TRAVEL",
    severity: "HIGH",
    timeWindowMinutes: 30,
    mitreTechniqueId: "T1078",
    mitreTechniqueName: "Valid Accounts",
    mitreTactic: "Initial Access",
    logicDescription: "The same user has successful logins from two different countries within 30 minutes.",
  },
  {
    ruleId: "RULE-NEW-DEVICE",
    name: "New Device Login",
    description: "Detects a successful login from a device never previously associated with the account.",
    detectionType: "NEW_DEVICE",
    severity: "MEDIUM",
    timeWindowMinutes: 5,
    mitreTechniqueId: "T1078",
    mitreTechniqueName: "Valid Accounts",
    mitreTactic: "Initial Access",
    logicDescription: "A user authenticates successfully from a device that is not in their known-device baseline.",
  },
  {
    ruleId: "RULE-ACCOUNT-TAKEOVER",
    name: "Account Takeover Indicator",
    description: "Correlates new IP + new device + failed logins + successful login + MFA change into one high-confidence alert.",
    detectionType: "ACCOUNT_TAKEOVER",
    severity: "CRITICAL",
    threshold: 4,
    timeWindowMinutes: 15,
    mitreTechniqueId: "T1078",
    mitreTechniqueName: "Valid Accounts",
    mitreTactic: "Initial Access",
    logicDescription: "At least 4 of: new IP, new device, prior failed logins, a successful login, and an MFA change, all for the same user within 15 minutes.",
  },
];

export const DEFAULT_PLAYBOOKS = [
  {
    detectionType: "PASSWORD_SPRAY",
    title: "Password Spray Playbook",
    steps: [
      "Validate source IP",
      "Review affected accounts",
      "Check for any successful authentication from that IP",
      "Determine whether any accounts were compromised",
      "Block or investigate the source IP",
      "Reset affected credentials if necessary",
      "Review MFA status for affected accounts",
      "Close incident after validation",
    ],
  },
  {
    detectionType: "MFA_ABUSE",
    title: "MFA Abuse Playbook",
    steps: [
      "Validate the MFA activity in the identity event log",
      "Review the user's recent login history",
      "Verify the user's identity through an out-of-band channel",
      "Check for device/IP changes around the same time",
      "Revoke suspicious active sessions",
      "Reset MFA enrollment if necessary",
      "Document the investigation",
    ],
  },
  {
    detectionType: "PRIVILEGE_ESCALATION",
    title: "Privilege Escalation Playbook",
    steps: [
      "Verify the role change in the audit log",
      "Identify the actor who made the change",
      "Determine whether the change was authorized",
      "Review the user's activity prior to the change",
      "Remove the unauthorized privilege if confirmed malicious",
      "Review the account's subsequent activity",
      "Document the incident",
    ],
  },
  {
    detectionType: "UNUSUAL_ADMIN_LOGIN",
    title: "Unusual Admin Login Playbook",
    steps: [
      "Confirm the login details (time, IP, device, location) with the admin",
      "Check whether the IP/device is associated with any known travel or remote work",
      "Review actions taken during the session",
      "If unauthorized, disable the account and force a password reset",
      "Review for any privilege changes made during the session",
      "Document findings and update the admin's baseline if legitimate",
    ],
  },
  {
    detectionType: "IMPOSSIBLE_TRAVEL",
    title: "Impossible Travel Playbook",
    steps: [
      "Confirm both login locations and timestamps",
      "Contact the user through a trusted channel to verify travel",
      "Check for VPN usage that could explain the discrepancy",
      "If unconfirmed, terminate active sessions and force re-authentication",
      "Reset credentials and MFA if compromise is suspected",
      "Document the investigation outcome",
    ],
  },
  {
    detectionType: "NEW_DEVICE",
    title: "New Device Login Playbook",
    steps: [
      "Confirm the device details with the account owner",
      "Check whether the login combined with other risk signals (new IP, odd hours)",
      "If confirmed legitimate, allow the baseline to update naturally",
      "If unconfirmed, terminate the session and force re-authentication",
      "Document the outcome",
    ],
  },
  {
    detectionType: "ACCOUNT_TAKEOVER",
    title: "Account Takeover Playbook",
    steps: [
      "Immediately review all correlated evidence events for the account",
      "Terminate all active sessions for the account",
      "Force a password reset and MFA re-enrollment",
      "Review any data or configuration changes made during the suspicious window",
      "Notify the account owner and their manager",
      "Escalate to full incident response if sensitive data was accessed",
      "Document the full timeline and response actions",
    ],
  },
];
