"use client";

import { useState } from "react";
import { RotateCcw, Zap, Trash2, Loader2 } from "lucide-react";
import AppShell from "@/components/layout/AppShell";
import { apiFetch } from "@/lib/apiClient";

export default function SettingsPage() {
  const [busy, setBusy] = useState(null);
  const [message, setMessage] = useState("");

  async function run(action, endpoint) {
    setBusy(action);
    setMessage("");
    try {
      const data = await apiFetch(endpoint, { method: "POST" });
      setMessage(data.message);
    } catch (err) {
      setMessage(err.message);
    } finally {
      setBusy(null);
    }
  }

  return (
    <AppShell allowedRoles={["ADMIN"]} title="Settings" subtitle="Demo data controls and platform configuration">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="sx-card p-4">
          <div className="text-sm font-semibold mb-1" style={{ color: "var(--sx-text)" }}>Generate Demo Attack</div>
          <p className="text-xs mb-3" style={{ color: "var(--sx-text-dim)" }}>
            Runs a random attack simulation scenario to freshen up the dashboard for a demo.
          </p>
          <button className="sx-btn sx-btn-primary" disabled={busy} onClick={() => run("generate", "/api/admin/generate-demo-attack")}>
            {busy === "generate" ? <Loader2 size={14} className="animate-spin" /> : <Zap size={14} />} Generate Demo Attack
          </button>
        </div>

        <div className="sx-card p-4">
          <div className="text-sm font-semibold mb-1" style={{ color: "var(--sx-text)" }}>Clear Demo Data</div>
          <p className="text-xs mb-3" style={{ color: "var(--sx-text-dim)" }}>
            Removes only simulated events/alerts generated by the Attack Simulator. Seed baseline data and accounts are preserved.
          </p>
          <button className="sx-btn" disabled={busy} onClick={() => run("clear", "/api/admin/reset-demo")}>
            {busy === "clear" ? <Loader2 size={14} className="animate-spin" /> : <Trash2 size={14} />} Clear Demo Data
          </button>
        </div>

        <div className="sx-card p-4 md:col-span-2">
          <div className="text-sm font-semibold mb-1" style={{ color: "var(--sx-text)" }}>Full Reset</div>
          <p className="text-xs mb-3" style={{ color: "var(--sx-text-dim)" }}>
            To fully reset the database (users, rules, all events/alerts) back to a fresh install, run{" "}
            <code className="font-mono px-1 rounded" style={{ background: "var(--sx-panel-2)" }}>npm run seed</code> from the project
            terminal. This is not exposed in the UI because it also resets user accounts.
          </p>
        </div>
      </div>

      {message && (
        <div className="sx-card p-3 mt-4 text-sm" style={{ color: "var(--sx-low)" }}>
          {message}
        </div>
      )}
    </AppShell>
  );
}
